from sympy import Symbol, solve, simplify, expand
from sympy.printing.ccode import ccode

Br = Symbol("Br")
Bi = Symbol("Bi")
wr = Symbol("wr")
wi = Symbol("wi")
xr = Symbol("xr")
xi = Symbol("xi")
yr = Symbol("yr")
yi = Symbol("yi")
zr = Symbol("zr")
zi = Symbol("zi")

solution = solve([Br**2*wr + Bi**2*wr + Br*xr - Bi*xi + Br*yr - Bi*yr + Bi*yi + zr,
                  Br**2*wi + Bi**2*wi + Br*xi + Bi*xr + Br*yi + zi], [Br, Bi])

# solution 0

# Br = (-wi*zr + wr*zi + (-Math.sqrt(-Math.pow(wi*xr + wi*yr - wr*xi - wr*yi, 2)*(4*(wi*wi)*(zr*zr) - 8*wi*wr*zi*zr + 4*wi*(xi*xi)*zi - 8*wi*xi*yi*zi + 8*wi*xi*yr*zi - 4*wi*xi*yr*zr + 4*wi*(xr*xr)*zi - 8*wi*xr*yi*zr + 8*wi*xr*yr*zi + 4*wi*xr*yr*zr + 4*wi*(yi*yi)*zi - 8*wi*yi*yr*zi - 4*wi*yi*yr*zr + 8*wi*(yr*yr)*zi + 4*(wr*wr)*(zi*zi) + 4*wr*(xi*xi)*zr + 8*wr*xi*yi*zr - 4*wr*xi*yr*zi + 4*wr*(xr*xr)*zr - 8*wr*xr*yi*zi + 4*wr*xr*yr*zi + 4*wr*(yi*yi)*zr - 4*wr*yi*yr*zi - (xi*xi*xi*xi) - 2*(xi*xi*xi)*yr - 2*(xi*xi)*(xr*xr) - 2*(xi*xi)*xr*yr + 2*(xi*xi)*(yi*yi) - 2*(xi*xi)*yi*yr - (xi*xi)*(yr*yr) - 2*xi*(xr*xr)*yr - 2*xi*xr*(yr*yr) + 2*xi*(yi*yi)*yr - 2*xi*yi*(yr*yr) - (xr*xr*xr*xr) - 2*(xr*xr*xr)*yr + 2*(xr*xr)*(yi*yi) - 2*(xr*xr)*yi*yr - (xr*xr)*(yr*yr) + 2*xr*(yi*yi)*yr - 2*xr*yi*(yr*yr) - (yi*yi*yi*yi) + 2*(yi*yi*yi)*yr - (yi*yi)*(yr*yr)))/(2*(wi*wi)*(xi*xi) - 4*(wi*wi)*xi*yi + 4*(wi*wi)*xi*yr + 2*(wi*wi)*(xr*xr) + 4*(wi*wi)*xr*yr + 2*(wi*wi)*(yi*yi) - 4*(wi*wi)*yi*yr + 4*(wi*wi)*(yr*yr) - 4*wi*wr*xi*yr - 8*wi*wr*xr*yi + 4*wi*wr*xr*yr - 4*wi*wr*yi*yr + 2*(wr*wr)*(xi*xi) + 4*(wr*wr)*xi*yi + 2*(wr*wr)*(xr*xr) + 2*(wr*wr)*(yi*yi)) + (2*(wi*wi)*xi*zr - 2*(wi*wi)*yi*zr + 2*(wi*wi)*yr*zr - 2*wi*wr*xi*zi + 2*wi*wr*xr*zr + 2*wi*wr*yi*zi - 2*wi*wr*yr*zi - wi*(xi*xi)*xr - wi*(xi*xi)*yr - wi*xi*xr*yr - wi*xi*(yr*yr) - wi*(xr*xr*xr) - 2*wi*(xr*xr)*yr + wi*xr*(yi*yi) - wi*xr*yi*yr - wi*xr*(yr*yr) + wi*(yi*yi)*yr - wi*yi*(yr*yr) - 2*(wr*wr)*xr*zi + wr*(xi*xi*xi) + wr*(xi*xi)*yi + wr*(xi*xi)*yr + wr*xi*(xr*xr) + wr*xi*xr*yr - wr*xi*(yi*yi) + 2*wr*xi*yi*yr + wr*(xr*xr)*yi + wr*xr*yi*yr - wr*(yi*yi*yi) + wr*(yi*yi)*yr)/(2*((wi*wi)*(xi*xi) - 2*(wi*wi)*xi*yi + 2*(wi*wi)*xi*yr + (wi*wi)*(xr*xr) + 2*(wi*wi)*xr*yr + (wi*wi)*(yi*yi) - 2*(wi*wi)*yi*yr + 2*(wi*wi)*(yr*yr) - 2*wi*wr*xi*yr - 4*wi*wr*xr*yi + 2*wi*wr*xr*yr - 2*wi*wr*yi*yr + (wr*wr)*(xi*xi) + 2*(wr*wr)*xi*yi + (wr*wr)*(xr*xr) + (wr*wr)*(yi*yi))))*(wi*xi - wi*yi + wi*yr + wr*xr))/(wi*xr + wi*yr - wr*xi - wr*yi)

# Bi = -Math.sqrt(-Math.pow(wi*xr + wi*yr - wr*xi - wr*yi, 2)*(4*(wi*wi)*(zr*zr) - 8*wi*wr*zi*zr + 4*wi*(xi*xi)*zi - 8*wi*xi*yi*zi + 8*wi*xi*yr*zi - 4*wi*xi*yr*zr + 4*wi*(xr*xr)*zi - 8*wi*xr*yi*zr + 8*wi*xr*yr*zi + 4*wi*xr*yr*zr + 4*wi*(yi*yi)*zi - 8*wi*yi*yr*zi - 4*wi*yi*yr*zr + 8*wi*(yr*yr)*zi + 4*(wr*wr)*(zi*zi) + 4*wr*(xi*xi)*zr + 8*wr*xi*yi*zr - 4*wr*xi*yr*zi + 4*wr*(xr*xr)*zr - 8*wr*xr*yi*zi + 4*wr*xr*yr*zi + 4*wr*(yi*yi)*zr - 4*wr*yi*yr*zi - (xi*xi*xi*xi) - 2*(xi*xi*xi)*yr - 2*(xi*xi)*(xr*xr) - 2*(xi*xi)*xr*yr + 2*(xi*xi)*(yi*yi) - 2*(xi*xi)*yi*yr - (xi*xi)*(yr*yr) - 2*xi*(xr*xr)*yr - 2*xi*xr*(yr*yr) + 2*xi*(yi*yi)*yr - 2*xi*yi*(yr*yr) - (xr*xr*xr*xr) - 2*(xr*xr*xr)*yr + 2*(xr*xr)*(yi*yi) - 2*(xr*xr)*yi*yr - (xr*xr)*(yr*yr) + 2*xr*(yi*yi)*yr - 2*xr*yi*(yr*yr) - (yi*yi*yi*yi) + 2*(yi*yi*yi)*yr - (yi*yi)*(yr*yr)))/(2*(wi*wi)*(xi*xi) - 4*(wi*wi)*xi*yi + 4*(wi*wi)*xi*yr + 2*(wi*wi)*(xr*xr) + 4*(wi*wi)*xr*yr + 2*(wi*wi)*(yi*yi) - 4*(wi*wi)*yi*yr + 4*(wi*wi)*(yr*yr) - 4*wi*wr*xi*yr - 8*wi*wr*xr*yi + 4*wi*wr*xr*yr - 4*wi*wr*yi*yr + 2*(wr*wr)*(xi*xi) + 4*(wr*wr)*xi*yi + 2*(wr*wr)*(xr*xr) + 2*(wr*wr)*(yi*yi)) + (2*(wi*wi)*xi*zr - 2*(wi*wi)*yi*zr + 2*(wi*wi)*yr*zr - 2*wi*wr*xi*zi + 2*wi*wr*xr*zr + 2*wi*wr*yi*zi - 2*wi*wr*yr*zi - wi*(xi*xi)*xr - wi*(xi*xi)*yr - wi*xi*xr*yr - wi*xi*(yr*yr) - wi*(xr*xr*xr) - 2*wi*(xr*xr)*yr + wi*xr*(yi*yi) - wi*xr*yi*yr - wi*xr*(yr*yr) + wi*(yi*yi)*yr - wi*yi*(yr*yr) - 2*(wr*wr)*xr*zi + wr*(xi*xi*xi) + wr*(xi*xi)*yi + wr*(xi*xi)*yr + wr*xi*(xr*xr) + wr*xi*xr*yr - wr*xi*(yi*yi) + 2*wr*xi*yi*yr + wr*(xr*xr)*yi + wr*xr*yi*yr - wr*(yi*yi*yi) + wr*(yi*yi)*yr)/(2*((wi*wi)*(xi*xi) - 2*(wi*wi)*xi*yi + 2*(wi*wi)*xi*yr + (wi*wi)*(xr*xr) + 2*(wi*wi)*xr*yr + (wi*wi)*(yi*yi) - 2*(wi*wi)*yi*yr + 2*(wi*wi)*(yr*yr) - 2*wi*wr*xi*yr - 4*wi*wr*xr*yi + 2*wi*wr*xr*yr - 2*wi*wr*yi*yr + (wr*wr)*(xi*xi) + 2*(wr*wr)*xi*yi + (wr*wr)*(xr*xr) + (wr*wr)*(yi*yi)))

# solution 1

# Br = (-wi*zr + wr*zi + (Math.sqrt(-Math.pow(wi*xr + wi*yr - wr*xi - wr*yi, 2)*(4*(wi*wi)*(zr*zr) - 8*wi*wr*zi*zr + 4*wi*(xi*xi)*zi - 8*wi*xi*yi*zi + 8*wi*xi*yr*zi - 4*wi*xi*yr*zr + 4*wi*(xr*xr)*zi - 8*wi*xr*yi*zr + 8*wi*xr*yr*zi + 4*wi*xr*yr*zr + 4*wi*(yi*yi)*zi - 8*wi*yi*yr*zi - 4*wi*yi*yr*zr + 8*wi*(yr*yr)*zi + 4*(wr*wr)*(zi*zi) + 4*wr*(xi*xi)*zr + 8*wr*xi*yi*zr - 4*wr*xi*yr*zi + 4*wr*(xr*xr)*zr - 8*wr*xr*yi*zi + 4*wr*xr*yr*zi + 4*wr*(yi*yi)*zr - 4*wr*yi*yr*zi - (xi*xi*xi*xi) - 2*(xi*xi*xi)*yr - 2*(xi*xi)*(xr*xr) - 2*(xi*xi)*xr*yr + 2*(xi*xi)*(yi*yi) - 2*(xi*xi)*yi*yr - (xi*xi)*(yr*yr) - 2*xi*(xr*xr)*yr - 2*xi*xr*(yr*yr) + 2*xi*(yi*yi)*yr - 2*xi*yi*(yr*yr) - (xr*xr*xr*xr) - 2*(xr*xr*xr)*yr + 2*(xr*xr)*(yi*yi) - 2*(xr*xr)*yi*yr - (xr*xr)*(yr*yr) + 2*xr*(yi*yi)*yr - 2*xr*yi*(yr*yr) - (yi*yi*yi*yi) + 2*(yi*yi*yi)*yr - (yi*yi)*(yr*yr)))/(2*(wi*wi)*(xi*xi) - 4*(wi*wi)*xi*yi + 4*(wi*wi)*xi*yr + 2*(wi*wi)*(xr*xr) + 4*(wi*wi)*xr*yr + 2*(wi*wi)*(yi*yi) - 4*(wi*wi)*yi*yr + 4*(wi*wi)*(yr*yr) - 4*wi*wr*xi*yr - 8*wi*wr*xr*yi + 4*wi*wr*xr*yr - 4*wi*wr*yi*yr + 2*(wr*wr)*(xi*xi) + 4*(wr*wr)*xi*yi + 2*(wr*wr)*(xr*xr) + 2*(wr*wr)*(yi*yi)) + (2*(wi*wi)*xi*zr - 2*(wi*wi)*yi*zr + 2*(wi*wi)*yr*zr - 2*wi*wr*xi*zi + 2*wi*wr*xr*zr + 2*wi*wr*yi*zi - 2*wi*wr*yr*zi - wi*(xi*xi)*xr - wi*(xi*xi)*yr - wi*xi*xr*yr - wi*xi*(yr*yr) - wi*(xr*xr*xr) - 2*wi*(xr*xr)*yr + wi*xr*(yi*yi) - wi*xr*yi*yr - wi*xr*(yr*yr) + wi*(yi*yi)*yr - wi*yi*(yr*yr) - 2*(wr*wr)*xr*zi + wr*(xi*xi*xi) + wr*(xi*xi)*yi + wr*(xi*xi)*yr + wr*xi*(xr*xr) + wr*xi*xr*yr - wr*xi*(yi*yi) + 2*wr*xi*yi*yr + wr*(xr*xr)*yi + wr*xr*yi*yr - wr*(yi*yi*yi) + wr*(yi*yi)*yr)/(2*((wi*wi)*(xi*xi) - 2*(wi*wi)*xi*yi + 2*(wi*wi)*xi*yr + (wi*wi)*(xr*xr) + 2*(wi*wi)*xr*yr + (wi*wi)*(yi*yi) - 2*(wi*wi)*yi*yr + 2*(wi*wi)*(yr*yr) - 2*wi*wr*xi*yr - 4*wi*wr*xr*yi + 2*wi*wr*xr*yr - 2*wi*wr*yi*yr + (wr*wr)*(xi*xi) + 2*(wr*wr)*xi*yi + (wr*wr)*(xr*xr) + (wr*wr)*(yi*yi))))*(wi*xi - wi*yi + wi*yr + wr*xr))/(wi*xr + wi*yr - wr*xi - wr*yi)

# Bi = Math.sqrt(-Math.pow(wi*xr + wi*yr - wr*xi - wr*yi, 2)*(4*(wi*wi)*(zr*zr) - 8*wi*wr*zi*zr + 4*wi*(xi*xi)*zi - 8*wi*xi*yi*zi + 8*wi*xi*yr*zi - 4*wi*xi*yr*zr + 4*wi*(xr*xr)*zi - 8*wi*xr*yi*zr + 8*wi*xr*yr*zi + 4*wi*xr*yr*zr + 4*wi*(yi*yi)*zi - 8*wi*yi*yr*zi - 4*wi*yi*yr*zr + 8*wi*(yr*yr)*zi + 4*(wr*wr)*(zi*zi) + 4*wr*(xi*xi)*zr + 8*wr*xi*yi*zr - 4*wr*xi*yr*zi + 4*wr*(xr*xr)*zr - 8*wr*xr*yi*zi + 4*wr*xr*yr*zi + 4*wr*(yi*yi)*zr - 4*wr*yi*yr*zi - (xi*xi*xi*xi) - 2*(xi*xi*xi)*yr - 2*(xi*xi)*(xr*xr) - 2*(xi*xi)*xr*yr + 2*(xi*xi)*(yi*yi) - 2*(xi*xi)*yi*yr - (xi*xi)*(yr*yr) - 2*xi*(xr*xr)*yr - 2*xi*xr*(yr*yr) + 2*xi*(yi*yi)*yr - 2*xi*yi*(yr*yr) - (xr*xr*xr*xr) - 2*(xr*xr*xr)*yr + 2*(xr*xr)*(yi*yi) - 2*(xr*xr)*yi*yr - (xr*xr)*(yr*yr) + 2*xr*(yi*yi)*yr - 2*xr*yi*(yr*yr) - (yi*yi*yi*yi) + 2*(yi*yi*yi)*yr - (yi*yi)*(yr*yr)))/(2*(wi*wi)*(xi*xi) - 4*(wi*wi)*xi*yi + 4*(wi*wi)*xi*yr + 2*(wi*wi)*(xr*xr) + 4*(wi*wi)*xr*yr + 2*(wi*wi)*(yi*yi) - 4*(wi*wi)*yi*yr + 4*(wi*wi)*(yr*yr) - 4*wi*wr*xi*yr - 8*wi*wr*xr*yi + 4*wi*wr*xr*yr - 4*wi*wr*yi*yr + 2*(wr*wr)*(xi*xi) + 4*(wr*wr)*xi*yi + 2*(wr*wr)*(xr*xr) + 2*(wr*wr)*(yi*yi)) + (2*(wi*wi)*xi*zr - 2*(wi*wi)*yi*zr + 2*(wi*wi)*yr*zr - 2*wi*wr*xi*zi + 2*wi*wr*xr*zr + 2*wi*wr*yi*zi - 2*wi*wr*yr*zi - wi*(xi*xi)*xr - wi*(xi*xi)*yr - wi*xi*xr*yr - wi*xi*(yr*yr) - wi*(xr*xr*xr) - 2*wi*(xr*xr)*yr + wi*xr*(yi*yi) - wi*xr*yi*yr - wi*xr*(yr*yr) + wi*(yi*yi)*yr - wi*yi*(yr*yr) - 2*(wr*wr)*xr*zi + wr*(xi*xi*xi) + wr*(xi*xi)*yi + wr*(xi*xi)*yr + wr*xi*(xr*xr) + wr*xi*xr*yr - wr*xi*(yi*yi) + 2*wr*xi*yi*yr + wr*(xr*xr)*yi + wr*xr*yi*yr - wr*(yi*yi*yi) + wr*(yi*yi)*yr)/(2*((wi*wi)*(xi*xi) - 2*(wi*wi)*xi*yi + 2*(wi*wi)*xi*yr + (wi*wi)*(xr*xr) + 2*(wi*wi)*xr*yr + (wi*wi)*(yi*yi) - 2*(wi*wi)*yi*yr + 2*(wi*wi)*(yr*yr) - 2*wi*wr*xi*yr - 4*wi*wr*xr*yi + 2*wi*wr*xr*yr - 2*wi*wr*yi*yr + (wr*wr)*(xi*xi) + 2*(wr*wr)*xi*yi + (wr*wr)*(xr*xr) + (wr*wr)*(yi*yi)))
